services:
  suppliersmanager.api:
    image: alexdrdeveloper01/suppliersmanagerapi
    build:
      context: .
      dockerfile: src/Applications/SuppliersManager.Api/Dockerfile
    ports:
      - "9000:8080"
      - "9001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
        - ./src/Applications/SuppliersManager.Api/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 28018:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
