services:
  suppliersmanager.api:
    image: alexdrdeveloper01/suppliersmanagerapi
    build:
      context: .
      dockerfile: src/Applications/SuppliersManager.Api/Dockerfile
    ports:
      - "7000:8080"
      - "7001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx


  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 28018:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
